server:
  port: 8101

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true

eureka:
  client:
    fetch-registry: true

feign:
  circuitbreaker:
    enabled: true
